[
    {
        "id": "Q1",
        "text": "Is completion of a ‘Pre-appointment risk analysis’ outstanding?'",
        "help": "",
        "weightingForDesign": 2,
        "weightingForRandA": 3,
        "appearsIn": 1,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q2",
        "text": "Are there residual hazards to consider from the pre-appointment analysis?",
        "help": "",
        "weightingForDesign": 2,
        "weightingForRandA": 3,
        "appearsIn": 1,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q3",
        "text": "Is agreement of fee(s) and/or fee structure(s) outstanding?",
        "help": "To include ALL fees - HL, specialist groups, outsourced design etc. Ensure all fee proposals are in the PMP (folder 01A-1)",
        "weightingForDesign": 2,
        "weightingForRandA": 1,
        "appearsIn": 1,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q4",
        "text": "Is agreement of the contract of appointment outstanding? ",
        "help": "Refer to the Partner if unsure.",
        "weightingForDesign": 2,
        "weightingForRandA": 3,
        "appearsIn": 1,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q5",
        "text": "Is clarification of HL duties outstanding?",
        "help": "Ensure all duties - HL, specialist groups, outsourced design etc. - are copied into the PMP (folder 01A-2)",
        "weightingForDesign": 2,
        "weightingForRandA": 3,
        "appearsIn": 1,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q6",
        "text": "Are HL duties likely to change, e.g. novation?",
        "help": "Clarified in HL appointment, otherwise refer to the partner.  If HL are to be novated, treat as a new contract - new fee, planning, duties, initial review etc.  All novated appointment related documentation should be saved in the PMP. ",
        "weightingForDesign": 2,
        "weightingForRandA": 1,
        "appearsIn": 1,
        "applicableWhen": 631,
        "attachments": ["imf50"],
        "other": "redflag"
    },
    {
        "id": "Q7",
        "text": "Is development of client briefing information outstanding?",
        "help": "In the absence of formal client briefing, confirm back to the client using Stage A/B Report. Ensure that all contracted parties are briefed - specialists outsourced design etc. Save all briefing documentationin the PMP folder 01A-3",
        "weightingForDesign": 3,
        "weightingForRandA": 4,
        "appearsIn": 2,
        "applicableWhen": 4087,
        "attachments": ["stageAB"],
        "other": "redflag"
    },
    {
        "id": "Q8",
        "text": "Is identification of appropriate legislative/standards/guides outstanding?",
        "help": "All applicable legislation and guides/ codes of practice etc., should be identified for all projects but is especially important for those that are outside the \"norm\" ",
        "weightingForDesign": 2,
        "weightingForRandA": 4,
        "appearsIn": 2,
        "applicableWhen": 4068,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q9",
        "text": "Has insufficient time been allowed for HL design?",
        "help": "Communicate your concern to to the partner and where appropriate, the wider project team. Note in the Risk Register",
        "weightingForDesign": 4,
        "weightingForRandA": 0,
        "appearsIn": 2,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q10",
        "text": "Is the design technically complex, or are there any special/unusually onerous technical requirements?",
        "help": "",
        "weightingForDesign": 2,
        "weightingForRandA": 0,
        "appearsIn": 2,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q11",
        "text": "Is the project subject to an onerous EPC, BREEAM, CSH etc. requirement?",
        "help": "",
        "weightingForDesign": 3,
        "weightingForRandA": 0,
        "appearsIn": 2,
        "applicableWhen": 2007,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q12",
        "text": "Any other related risk?",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 2,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q13",
        "text": "Are other EM requirements??'",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 2,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q14",
        "text": "Is clarification of the scope of HL engineering services outstanding?",
        "help": "For all disciplines and all contracted parties - specialist groups, outsourced design etc. Save in the PMP folder 01A-2",
        "weightingForDesign": 2,
        "weightingForRandA": 4,
        "appearsIn": 4,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q15",
        "text": "Are the services as clarified outside HL normal scope? ",
        "help": "If they are, refer to partner.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 4,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q16",
        "text": "Is the project subject to CDM?",
        "help": "Note: virtually all non-domestic projects involving an element of design will be subject to CDM. the only question will be whether it is notifiable or not. - Refer to the HL \"CDM Handbook",
        "weightingForDesign": 3,
        "weightingForRandA": 0,
        "appearsIn": 4,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q17",
        "text": "Has the project been notified?",
        "help": "Note: whilst project notification under CDM  is to be completed by the CDM-C, notification does involve HL in additional duties. Refer to the HL CDM Handbook.",
        "weightingForDesign": 2,
        "weightingForRandA": 0,
        "appearsIn": 4,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q18",
        "text": "Any other related risk?",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 4,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q19",
        "text": "Are the services of Public Utilities Bodies required?",
        "help": "Include on the Risk Register only when seen as a risk- long lead time, excessive cost etc.",
        "weightingForDesign": 1,
        "weightingForRandA": 0,
        "appearsIn": 8,
        "applicableWhen": 1527,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q20",
        "text": "Is there a requirement for long lead equipment?",
        "help": "",
        "weightingForDesign": 1,
        "weightingForRandA": 0,
        "appearsIn": 8,
        "applicableWhen": 1527,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q21",
        "text": "Does the design involve innovation and/or un-tested features or equipment?",
        "help": "As a default, always specify within the applicable British, European and European Standards, Codes or Practice, design guides etc. Do not operate outside this criteria without authorisation of the partner.",
        "weightingForDesign": 1,
        "weightingForRandA": 0,
        "appearsIn": 8,
        "applicableWhen": 1527,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q22",
        "text": "Is there any risk resulting from the procurement method?",
        "help": "Such as pre-fabrication, contractor's equipment supply arrangements etc.",
        "weightingForDesign": 1,
        "weightingForRandA": 0,
        "appearsIn": 8,
        "applicableWhen": 1527,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q23",
        "text": "Does the project involve phased hand-over?",
        "help": "Note details in the risk register where phased handover results in risk",
        "weightingForDesign": 1,
        "weightingForRandA": 0,
        "appearsIn": 8,
        "applicableWhen": 1527,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q24",
        "text": "Any other related risk?",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 8,
        "applicableWhen": 1527,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q25",
        "text": "Does the location result in risk? ",
        "help": "Note in the risk register where the location results in risk - either inherentley or due to the proximity of adjacent buildings, natural features such as waterways etc. Note site constraints where they result in risk.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 16,
        "applicableWhen": 3569,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q26",
        "text": "Are existing engineering services present?",
        "help": "Always request information from the client or his representative - as per the CDM Regulations. Note in the risk register where existing services result in risk.",
        "weightingForDesign": 1,
        "weightingForRandA": 2,
        "appearsIn": 16,
        "applicableWhen": 3569,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q27",
        "text": "Do site visits form part of HL duties? ",
        "help": "Always complete a site visit risk assessment and send to the client, HL standard site visit HS enquiries.",
        "weightingForDesign": 1,
        "weightingForRandA": 3,
        "appearsIn": 16,
        "applicableWhen": 3569,
        "attachments": [],
        "other": "redflag"
    },
    {
        "id": "Q28",
        "text": "Any other related risk?",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 16,
        "applicableWhen": 3569,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q29",
        "text": "Does the current building use result in risk? ",
        "help": "Residential, commercial, retail, process, mixed use etc.  Note only where use results in risk.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q30",
        "text": "Is asbestos or asbestos containing materials present?",
        "help": "Always confirm with the client as part of the site visit risk assessment.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q31",
        "text": "Is the building unoccupied or derelict?",
        "help": "Note whether building is occupied, un-occupied, derelict etc.  Consider as part of the site visit risk register as appropriate.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q32",
        "text": "Do site visits form part of HL duties? ",
        "help": "Always complete a site visit risk assessment and send to the client, HL standard site visit HS enquires.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": ["IMF55"],
        "other": "redflag"
    },
    {
        "id": "Q33",
        "text": "Is there any distinguishing feature(s) of the building that may lead to risk?",
        "help": "Retained MEP services, areas to be kept operational during construction, retained architectural features such as high towers or chimneys etc. Areas that need to be accessed such as roof tops, basements, buildings service voids etc.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q34",
        "text": "Does the building contain COSHH materials, hazardous areas?",
        "help": "Such as confined spaces, explosive areas etc. Consider as part of the site visit risk assessment",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q35",
        "text": "Any other related risk?",
        "help": "",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 32,
        "applicableWhen": 2550,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q36",
        "text": "Are project-specific (QM) procedures required for the project?",
        "help": "Typically for issue of information, review, change, information referencing and/or numbering etc.  Consider appointing a dedicated QM manager or document controller dependant on significance of departure from standard HL practice.",
        "weightingForDesign": 1,
        "weightingForRandA": 1,
        "appearsIn": 64,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q37",
        "text": "Is significant change likely to either the project or the appointment?",
        "help": "Use a change control register to manage.",
        "weightingForDesign": 3,
        "weightingForRandA": 1,
        "appearsIn": 64,
        "applicableWhen": 4087,
        "attachments": [],
        "other": "redflag"
    },
    {
        "id": "Q38",
        "text": "Is any design or related work to be outsourced by HL?",
        "help": "It is essential to assess the competency and capability of external organisations sub-contracted by HL.  Use standard template IMF68. Note there is no requirement to assess competence of a particular organisation if already completed on a similar project ",
        "weightingForDesign": 3,
        "weightingForRandA": 5,
        "appearsIn": 64,
        "applicableWhen": 4087,
        "attachments": [],
        "other": "redflag"
    },
    {
        "id": "Q39",
        "text": "Is CDM ‘pre-construction’ information from other parties outstanding and/or inadequate?",
        "help": "From either the client or CDM-C.",
        "weightingForDesign": 2,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q40",
        "text": "Is BIM to be used for this Project?",
        "help": "Confirm with Partner",
        "weightingForDesign": 3,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 1975,
        "attachments": [],
        "other": "redflag"
    },
    {
        "id": "Q41",
        "text": "Is preparation of a BIM Project Execution Plan outstanding?",
        "help": "To be prepared by the Project Leader in conjunction with the HL BIM Coordinator.",
        "weightingForDesign": 2,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 1875,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q42",
        "text": "Any other BIM related risk?",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 1975,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q43",
        "text": "Is IES or another modelling package to be used for this Project?",
        "help": "",
        "weightingForDesign": 4,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 2039,
        "attachments": [],
        "other": "redflag"
    },
    {
        "id": "Q44",
        "text": "Is a thorough briefing to the modeller(s) outstanding?",
        "help": "",
        "weightingForDesign": 4,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q45",
        "text": "Is a model review strategy (by the modeller) outstanding?",
        "help": "",
        "weightingForDesign": 2,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q46",
        "text": "Any other IES related risk?",
        "help": "",
        "weightingForDesign": 0,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 2039,
        "attachments": [],
        "other": ""
    },
    {
        "id": "Q47",
        "text": "Is there any further information outstanding or required by HL?",
        "help": "",
        "weightingForDesign": 3,
        "weightingForRandA": 0,
        "appearsIn": 64,
        "applicableWhen": 4087,
        "attachments": [],
        "other": ""
    }
]